complete Lead and some change in Account
DimaZaitsau/Salecforce_QA22_Dima_Zaytsev pull request #3
Opened 2023-01-16 20:47 UTC by DimaZaitsau

2023-01-17 09:30 UTC, voropa commented on src/test/java/elements/Account/Input.java
> +public class Input extends BaseElement {
Вы уверены, что для Account нужны другие декораторы, не работают те, которые для Lead?

2023-01-22 18:43 UTC, voropa requested changes

2023-01-22 18:43 UTC, voropa commented on pom.xml
> +    <dependency>
У вас 2 раза дублируется зависимость org.projectlombok

2023-01-22 18:43 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    private final static By SAVE_BUTTON_FOR_ACCOUNT_MODAL = By.xpath("//div[@class='button-container-inner slds-float_right']//span[text()='Save']");
Вот так делать неправильно. Мы же создем Base классы и наследуем отсальные от них как раз для таких случаев, чтобы можно было переопределить в классе наследнике необходимые поля/методы. Так что правильным рещением будет просто переопределить лдокатор для save button в классе AccountModal

2023-01-22 18:43 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    public void waitSaveButtonForAccountModalPresent()  {
Соответсвенно эти методы тут будут не нужны

2023-01-22 18:43 UTC, voropa commented on src/test/java/tests/AccountsTest.java
> +        Faker faker = new Faker();
Лучше обьявить и проинициализировать этот обьект в BaseTest классе, чтобы не  прииходилось дублировать это в каждом test клссе

2023-01-23 20:10 UTC, voropa requested changes

2023-01-23 20:10 UTC, voropa commented on src/test/java/modals/NewAccountModal.java
> +    private final static By ACCOUNT_SAVE_BUTTON = By.xpath("//button" +
Правильно вообще даже не зводить новую перемненную (поле класса) для этой кнопки, а просто сделать SAVE_BUTTON protected в base  классе и переопределить локатор тут

2023-01-23 20:10 UTC, voropa commented on src/test/java/tests/LeadsTests.java
> +        Thread.sleep(3000);
Почему thread.sleep'ы?
Замените их на явные ожидания

2023-02-01 19:21 UTC, voropa requested changes

2023-02-01 19:21 UTC, voropa commented on src/test/java/tests/AccountsTest.java
> +        newAccountModal.clickSaveButton();
А тут нужно кликать на  save,  перед тем, как заполнить форму?

2023-02-01 19:23 UTC, voropa commented
Работают тесты, проходят все?

2023-02-01 19:39 UTC, DimaZaitsau commented on src/test/java/tests/AccountsTest.java
> +        newAccountModal.clickSaveButton();
убрал этот save

2023-02-01 19:42 UTC, voropa requested changes

2023-02-01 19:42 UTC, voropa commented on src/test/java/tests/ContactsTest.java
> +                .setMobile(faker.phoneNumber().cellPhone()).setAccountName("Emiko Mann").setTitle("qwerty")
Вот еще косяк заметил. Когда  у себя пыптаюсь запустить, этот тест падает, потому что нет у меня такого account с именем "Emiko Mann", а тесты должны быть самодостаточными и проходить на любом энвайроменте. Так что правильным решением в данном случае будет создавать новый аккаунт в пре-кондишине к этому тесту и ссылаться именно на него тут

2023-02-01 22:00 UTC, voropa approved these changes

2023-02-03 15:19 UTC, merged